run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 15
    skip-tests: true
  lll:
    line-length: 130
  gofumpt:
    extra-rules: true
  gosec:
    excludes:
      - G101
      - G402
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: pascal

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - gocyclo # duplicate of cyclop
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - depguard
    - dupl
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - gomnd
    - gomoddirectives
    - ireturn
    - lll
    - nlreturn
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    - "ST1000: at least one file in a package should have a package comment"
    - "package-comments: should have a package comment"
