project_name: terraform-provider-ec
dist: dist

env:
  - CGO_ENABLED=0

builds:
  - id: terraform-provider-ec
    binary: "terraform-provider-ec_{{ .Version }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

changelog:
  skip: true

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

signs:
  - artifacts: checksum
    stdin: '{{ .Env.GPG_PASSWORD }}'
    args:
      - "--batch"
      - "--no-tty"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - '{{ .Env.GPG_PASSWORD }}'
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

snapshot:
  name_template: 'dev-{{ slice .FullCommit 0 8}}'
