package testdata

// Code generated by schema-gen. DO NOT EDIT.

import "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

func testObjectSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"bool": {
			Type:     schema.TypeBool,
			Required: true,
		},
		"cpu": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"float": {
			Type:     schema.TypeFloat,
			Optional: true,
		},
		"int": {
			Type:     schema.TypeInt,
			Computed: true,
		},
		"map": {
			Type:     schema.TypeMap,
			Optional: true,
			Elem:     &schema.Schema{Type: schema.TypeInt},
		},
		"metadata": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem:     &schema.Resource{Schema: metadataSchema()},
		},
		"slice": {
			Type:     schema.TypeList,
			Optional: true,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"a": {
						Type:     schema.TypeString,
						Optional: true,
					},
				},
			},
		},
		"str": {
			Type:        schema.TypeString,
			Description: "String docs",
			Optional:    true,
		},
		"struct": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"a": {
						Type:     schema.TypeString,
						Optional: true,
					},
				},
			},
		},
	}
}
