package protection

// Code generated by schema-gen. DO NOT EDIT.

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/nitrado/terraform-provider-ec/ec/meta"
)

func gatewayPolicySchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"instance": {
			Type:        schema.TypeString,
			Description: "Name is an instance name configured in the provider.",
			Optional:    true,
		},
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: meta.Schema()},
		},
		"spec": {
			Type:        schema.TypeList,
			Description: "Spec defines the desired gateway policy.",
			Optional:    true,
			MaxItems:    1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"description": {
						Type:        schema.TypeString,
						Description: "Description is the optional gateway policy description.",
						Optional:    true,
					},
					"destination_cidrs": {
						Type:        schema.TypeList,
						Description: "DestinationCIDRs contain the CIDRs that should use the gateway.",
						Required:    true,
						Elem:        &schema.Schema{Type: schema.TypeString},
					},
					"display_name": {
						Type:        schema.TypeString,
						Description: "DisplayName is the display name of the gateway policy.",
						Optional:    true,
					},
				},
			},
		},
	}
}
