package protection

// Code generated by schema-gen. DO NOT EDIT.

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/nitrado/terraform-provider-ec/ec/meta"
)

func migrationSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"instance": {
			Type:        schema.TypeString,
			Description: "Name is an instance name configured in the provider.",
			Optional:    true,
		},
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: meta.Schema()},
		},
		"spec": {
			Type:        schema.TypeList,
			Description: "Spec defines the desired mitigation configuration.",
			Optional:    true,
			MaxItems:    1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"description": {
						Type:        schema.TypeString,
						Description: "Description is the optional description of the mitigation.",
						Optional:    true,
					},
					"display_name": {
						Type:        schema.TypeString,
						Description: "DisplayName is the user-friendly name of the mitigation.",
						Optional:    true,
					},
					"sts": {
						Type:        schema.TypeList,
						Description: "StS configures SteelShield for this mitigation.",
						Optional:    true,
						MaxItems:    1,
						Elem: &schema.Resource{
							Schema: map[string]*schema.Schema{
								"action": {
									Type:        schema.TypeString,
									Description: "Action is the configured SteelShield action.",
									Optional:    true,
								},
								"protocol": {
									Type:        schema.TypeString,
									Description: "Protocol is the protocol that the mitigation supports.",
									Optional:    true,
								},
							},
						},
					},
				},
			},
		},
	}
}
