package armada

// Code generated by schema-gen. DO NOT EDIT.

import "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

func branchSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: metadataSchema()},
		},
		"spec": {
			Type:        schema.TypeList,
			Description: "Spec defines the desired branch.",
			Optional:    true,
			MaxItems:    1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"description": {
						Type:        schema.TypeString,
						Description: "Description is the optional description of the branch.",
						Optional:    true,
					},
					"display_name": {
						Type:        schema.TypeString,
						Description: "DisplayName is the display name of the branch.",
						Optional:    true,
					},
				},
			},
		},
	}
}
