package core

// Code generated by schema-gen. DO NOT EDIT.

import "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

func resourcesSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"cpu": {
			Type:        schema.TypeString,
			Description: "CPU is the CPU resource.",
			Optional:    true,
		},
		"memory": {
			Type:        schema.TypeString,
			Description: "Memory is the Memory resource.",
			Optional:    true,
		},
	}
}
