package core

// Code generated by schema-gen. DO NOT EDIT.

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/nitrado/terraform-provider-ec/ec/meta"
)

func environmentSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: meta.Schema()},
		},
		"spec": {
			Type:        schema.TypeList,
			Description: "Spec configures the environment.",
			Optional:    true,
			MaxItems:    1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"description": {
						Type:        schema.TypeString,
						Description: "Description is the description of the environment.",
						Optional:    true,
					},
					"display_name": {
						Type:        schema.TypeString,
						Description: "DisplayName is friendly name of the environment.",
						Optional:    true,
					},
				},
			},
		},
	}
}
