package core

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/nitrado/terraform-provider-ec/ec/meta"
)

// secretSchema is not generated by the schema generator.
// It has special requirements that are not supported by the generator.
func secretSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"instance": {
			Type:        schema.TypeString,
			Description: "Name is an instance name configured in the provider.",
			Optional:    true,
		},
		"data": {
			Type:        schema.TypeMap,
			Description: "Data contains the secret data. Each key must consist of alphanumeric\ncharacters, '-', '_' or '.'. The total bytes of the values in the Data\nfield must be less than 1MB.",
			Required:    true,
			Sensitive:   true,
			Elem:        &schema.Schema{Type: schema.TypeString},
		},
		"description": {
			Type:        schema.TypeString,
			Description: "Description is the optional description of the config file.",
			Optional:    true,
		},
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: meta.Schema()},
		},
	}
}
