package storage

// Code generated by schema-gen. DO NOT EDIT.

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/nitrado/terraform-provider-ec/ec/meta"
)

func volumeStoreSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"instance": {
			Type:        schema.TypeString,
			Description: "Name is an instance name configured in the provider.",
			Optional:    true,
		},
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: meta.Schema()},
		},
		"spec": {
			Type:        schema.TypeList,
			Description: "Spec defines the desired volume.",
			Optional:    true,
			MaxItems:    1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"destination": {
						Type:        schema.TypeString,
						Description: "Destination is the destination storage location.",
						Required:    true,
					},
					"max_volume_size": {
						Type:        schema.TypeString,
						Description: "MaxVolumeSize is the maximum size of a volume in the volume store.",
						Required:    true,
					},
					"region": {
						Type:        schema.TypeString,
						Description: "Region is the region the volume store resides in.",
						Required:    true,
					},
				},
			},
		},
	}
}
