package storage

// Code generated by schema-gen. DO NOT EDIT.

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/nitrado/terraform-provider-ec/ec/meta"
)

func volumeStoreRetentionPolicySchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"instance": {
			Type:        schema.TypeString,
			Description: "Name is an instance name configured in the provider.",
			Optional:    true,
		},
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: meta.Schema()},
		},
		"spec": {
			Type:        schema.TypeList,
			Description: "Spec defines the desired volume store retention policy.",
			Optional:    true,
			MaxItems:    1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"snapshots": {
						Type:        schema.TypeList,
						Description: "Snapshots defines the retention policy for volume snapshots.",
						Optional:    true,
						MaxItems:    1,
						Elem: &schema.Resource{
							Schema: map[string]*schema.Schema{
								"offline_count": {
									Type:        schema.TypeInt,
									Description: "OfflineCount is the minimum number of offline snapshots to keep.",
									Optional:    true,
								},
								"offline_days": {
									Type:        schema.TypeInt,
									Description: "OfflineDays is the minimum number of days to keep an offline snapshot.",
									Optional:    true,
								},
								"online_count": {
									Type:        schema.TypeInt,
									Description: "OnlineCount is the minimum number of online snapshots to keep.",
									Optional:    true,
								},
								"online_days": {
									Type:        schema.TypeInt,
									Description: "OnlineDays is the minimum number of days to keep an online snapshot.",
									Optional:    true,
								},
							},
						},
					},
					"volume_store_name": {
						Type:        schema.TypeString,
						Description: "VolumeStoreName is the name of the volume store this volume uses.",
						Required:    true,
					},
				},
			},
		},
	}
}
