package container

// Code generated by schema-gen. DO NOT EDIT.

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/nitrado/terraform-provider-ec/ec/meta"
)

func branchSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"instance": {
			Type:        schema.TypeString,
			Description: "Name is an instance name configured in the provider.",
			Optional:    true,
		},
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: meta.Schema()},
		},
		"spec": {
			Type:        schema.TypeList,
			Description: "Spec defines the desired branch.",
			Optional:    true,
			MaxItems:    1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"description": {
						Type:        schema.TypeString,
						Description: "Description is the optional description of the branch.",
						Optional:    true,
					},
					"display_name": {
						Type:        schema.TypeString,
						Description: "DisplayName is the display name of the branch.",
						Optional:    true,
					},
					"retention_policy_rules": {
						Type:        schema.TypeList,
						Description: "RetentionPolicyRules are the rules that define how images are retained.",
						Optional:    true,
						Elem: &schema.Resource{
							Schema: map[string]*schema.Schema{
								"image_regex": {
									Type:        schema.TypeString,
									Description: "ImageRegex is the optional regex selector for images that\nthis policy applies to.",
									Optional:    true,
								},
								"keep_count": {
									Type:        schema.TypeInt,
									Description: "KeepCount is the minimum number of tags to keep per image.",
									Optional:    true,
								},
								"keep_days": {
									Type:        schema.TypeInt,
									Description: "KeepDays is the minimum number of days an image tag must be kept for.",
									Optional:    true,
								},
								"name": {
									Type:        schema.TypeString,
									Description: "Name is the name of the image retention policy.",
									Required:    true,
								},
								"tag_regex": {
									Type:        schema.TypeString,
									Description: "TagRegex is the optional regex selector for tags that\nthis policy applies to.",
									Optional:    true,
								},
							},
						},
					},
				},
			},
		},
	}
}
