package authentication

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/nitrado/terraform-provider-ec/ec/meta"
)

// serviceAccountSchema is not generated by the schema generator.
// It has special requirements that are not supported by the generator.
func serviceAccountSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"instance": {
			Type:        schema.TypeString,
			Description: "Name is an instance name configured in the provider.",
			Optional:    true,
			ForceNew:    true,
		},
		"metadata": {
			Type:        schema.TypeList,
			Description: "Standard object's metadata.",
			Optional:    true,
			ForceNew:    true,
			MaxItems:    1,
			Elem:        &schema.Resource{Schema: meta.Schema()},
		},
		"spec": {
			Type:        schema.TypeList,
			Description: "Spec defines the desired state of the service account.",
			Optional:    true,
			ForceNew:    true,
			MaxItems:    1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"email": {
						Type:        schema.TypeString,
						Description: "Email specifies the email address associated with the service account.",
						Required:    true,
					},
					"username": {
						Type:        schema.TypeString,
						Description: "Username is the name of the service account.",
						Required:    true,
					},
				},
			},
		},
		"password": {
			Type:        schema.TypeString,
			Description: "Password is the clear text password of the service account generated by the API Server. This is only returned on create.",
			Computed:    true,
			Sensitive:   true,
		},
	}
}
